"""initial migration

Revision ID: a3049dabbb82
Revises: 4fbb8e9f2d01
Create Date: 2021-04-05 21:07:11.576772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3049dabbb82'
down_revision = '4fbb8e9f2d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('puppies', 'age')
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.TEXT(), nullable=True))
    op.add_column('puppies', sa.Column('age', sa.INTEGER(), nullable=True))
    op.drop_table('toys')
    op.drop_table('owners')
    # ### end Alembic commands ###
